### ISSUE TITLE
/define is case sensitive

### ISSUE THREAD

**Issue by lara-rium** [freepizzas-dev/onebot#7] opened 2023-09-05 00:03 UTC
in other words, `/define foo` doesn't yield the same result as `/define Foo`, in most cases, the latter doesn't return any response

rarely case does matter (as in `/define Foo` does return a response), so i think it'd be nice if it showed results for both lowercase (priority) and title case definitions

**Comment by freepizzas-dev** [comment] 2023-09-09 05:31
Hi, thanks so much for taking the time to file an issue for oneBot!

Indeed, the /define and /etym commands are case sensitive by design. Users need a way to specify whether or not they're looking up a capitalized or lowercase definition in case of overlap.

But you're entirely correct that in (probably) 99.9% of cases, it doesn't matter. The majority of words on Wiktionary don't have case overlap like that. I think the best solution is to check for the case the user specifies first, then check the other case if there are no results and return that if it has a match.

Unless someone has a major issue with it, I'll be committing a patch to that effect within a few days, and the public version of oneBot will pick it up within a few days after that.

**Comment by freepizzas-dev** [comment] 2023-09-11 17:27
Resolved in https://github.com/freepizzas-dev/onebot/commit/61a9c96a94f3314a3b8493ebff699fb5d43311e1

**Closed as completed by freepizzas-dev** 2023-09-11 17:27 UTC
